In [1]:
import torch
import torch.nn as nn

In [4]:
x=torch.tensor([[1,2],
                [2,2],
                [3,3],
                [4,5]], dtype=torch.float32)
x.shape

torch.Size([4, 2])

In [45]:
x=torch.tensor([[1],
                [2],
                [3],
                [4]], dtype=torch.float32)
y=torch.tensor([[2],
                [4],
                [6],
                [8]], dtype=torch.float32)

no_of_samples, no_of_features = x.shape

input_size = no_of_features
output_size = 1

#model = nn.Linear(input_size, output_size)
model = LinearRegression(input_size, output_size)

x_test = torch.tensor([5], dtype=torch.float32)
print("Prediction before training : f(5) = ",model(x_test).item())

# Training
learning_rate = 0.01
no_of_iters = 100

loss = nn.MSELoss() # We are defining a MSE Loss function using nn, because Linear Regression uses MSE Loss function
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate) #Stochastic Gradient Descent

for epoch in range(no_of_iters):
    # Prediction
    y_pred = model(x)

    # Loss
    l = loss(y, y_pred)

    # Gradients = backward pass
    l.backward()
    
    # Update weights
    optimizer.step()

    # Zero gradients
    optimizer.zero_grad()
    
    [w, b] = model.parameters() #w is wights and b is optional bias
    print("epoch", epoch + 1, ": w = ", w, " loss = ", l.item())

print("Prediction after training : f(5) = ", model(x_test).item())

Prediction before training : f(5) =  -0.6317664384841919
epoch 1 : w =  Parameter containing:
tensor([[0.0651]], requires_grad=True)  loss =  31.546764373779297
epoch 2 : w =  Parameter containing:
tensor([[0.3213]], requires_grad=True)  loss =  21.962167739868164
epoch 3 : w =  Parameter containing:
tensor([[0.5350]], requires_grad=True)  loss =  15.311190605163574
epoch 4 : w =  Parameter containing:
tensor([[0.7132]], requires_grad=True)  loss =  10.695783615112305
epoch 5 : w =  Parameter containing:
tensor([[0.8618]], requires_grad=True)  loss =  7.492823600769043
epoch 6 : w =  Parameter containing:
tensor([[0.9857]], requires_grad=True)  loss =  5.269931316375732
epoch 7 : w =  Parameter containing:
tensor([[1.0892]], requires_grad=True)  loss =  3.7270889282226562
epoch 8 : w =  Parameter containing:
tensor([[1.1756]], requires_grad=True)  loss =  2.656123399734497
epoch 9 : w =  Parameter containing:
tensor([[1.2478]], requires_grad=True)  loss =  1.9125850200653076
epoch 10 :

In [44]:
class LinearRegression(nn.Module):

    def __init__(self, input_dim, output_dim) -> None:
        super().__init__()
        self.lin = nn.Linear(input_dim, output_dim)
    
    def forward(self,x):
        return self.lin(x)
'''
In PyTorch, defining the forward function within a custom neural network class, such as the one inheriting from nn.Module, is crucial for several reasons:

Forward Pass Definition:

The primary purpose of the forward method is to define how the input data flows through the network layers during the forward pass. It specifies the sequence of operations that transform the input into the output.
Automatic Differentiation:

PyTorch uses dynamic computational graphs for automatic differentiation. When you call the forward method, PyTorch builds the computation graph, which is essential for computing gradients during the backward pass (gradient computation for training).
Backward Pass Computation:

The forward method, along with the autograd system in PyTorch, allows the framework to automatically track operations during the forward pass. This information is then used to compute gradients during the backward pass, which is necessary for training the model.
Parameter Update:

During training, the parameters (weights and biases) of the neural network are updated based on the gradients computed during the backward pass. The forward method is critical for establishing the connections between input, parameters, and output, enabling the computation of these gradients.
Model Behavior Specification:

The forward method encapsulates the behavior of the model. When you call the model instance with input data, such as output = model(input), it's the forward method that gets executed, defining how the model processes the input.
Layer Composition:

For models with multiple layers or submodules, the forward method specifies the order in which these layers are applied to the input data. This ensures that the data flows correctly through the network.
Custom Operations:

If your model includes custom operations or non-linearities, you can include them in the forward method. This allows you to define complex architectures beyond simple layer stacking.
Code Clarity:

Explicitly defining the forward method makes your code more readable and intuitive. It clearly indicates the sequence of operations that make up the forward pass, making it easier for others (and yourself) to understand the model's behavior.
'''