In [ ]:
import torch

In [ ]:
x=torch.empty(3) #create an empty tensor
print(x)

x=torch.empty(2,3)
print(x)

x=torch.empty(2,2,3)
print(x)

x=torch.empty(2,2,2,3)
print(x)

In [ ]:
x=torch.rand(2,3)
print(x)

x=torch.zeros(3,2)
print(x)
print(x.dtype) #gives datatype of the tensor

In [ ]:
#By Default, the datatype is float32.
#But we can always assign a datatype to the tensor as follows
x=torch.ones(2,3,dtype=torch.double) #Other dtypes are torch.int, torch.float16, etc
print(x)
print(x.dtype)
print(x.size()) #returns size of the tensor

In [ ]:
#Creating tensors from data
x=torch.tensor([2.5,0.1,3]) #from list
print(x)
print(x.size())
print(x.dtype)

In [ ]:
x=torch.rand(2,3)
y=torch.rand(2,3)
print(x)
print(y)
z=x+y
print(z)

x=torch.rand(2,3)
y=torch.rand(3,2)
print(x)
print(y)
z=x+y
print(z)

In [ ]:
x=torch.rand(2,3)
y=torch.rand(2,3)
print(x)
print(y)
z=torch.add(x,y) #same as z=x+y
print(z)

In [ ]:
x=torch.rand(2,3)
y=torch.rand(2,3)
print(x)
print(y)
y.add_(x) #same as y=y+x
print(y)

In [ ]:
x=torch.rand(2,3)
y=torch.rand(2,3)
print(x)
print(y)
z=torch.sub(x,y) #same as z=x-y
print(z)
z=torch.mul(x,y) #same as z=x*y
print(z)
z=torch.div(x,y) #same as z=x/y
print(z)

In [23]:
x=torch.rand(5,3)
print(x)
print(x[1,2:3])  #slicing of tensors
print(x[:,1])
print(x[:5,:2])

print(x[1,1].item())

tensor([[0.9133, 0.5448, 0.0954],
        [0.9390, 0.2067, 0.1451],
        [0.5356, 0.7338, 0.4305],
        [0.8893, 0.5855, 0.4680],
        [0.0415, 0.1799, 0.9745]])
tensor([0.1451])
tensor([0.5448, 0.2067, 0.7338, 0.5855, 0.1799])
tensor([[0.9133, 0.5448],
        [0.9390, 0.2067],
        [0.5356, 0.7338],
        [0.8893, 0.5855],
        [0.0415, 0.1799]])
0.20673322677612305


In [26]:
#reshaping a tensor
x=torch.rand(4,4) #implies that there are 4*4 = 16 values
print(x)
print(x.size())

y=x.view(16) #total values = 16 (has to be same in both cases for re-shaping)
print(y)
print(y.size())

z=x.view(-1,8) # put -1 if you don't know the dimension. pytorch can determine automatically
print(z)
print(z.size())


tensor([[0.8227, 0.1837, 0.1123, 0.4316],
        [0.4505, 0.2199, 0.3200, 0.5095],
        [0.4429, 0.9919, 0.2892, 0.1542],
        [0.2552, 0.4149, 0.3397, 0.4137]])
torch.Size([4, 4])
tensor([0.8227, 0.1837, 0.1123, 0.4316, 0.4505, 0.2199, 0.3200, 0.5095, 0.4429,
        0.9919, 0.2892, 0.1542, 0.2552, 0.4149, 0.3397, 0.4137])
torch.Size([16])
tensor([[0.8227, 0.1837, 0.1123, 0.4316, 0.4505, 0.2199, 0.3200, 0.5095],
        [0.4429, 0.9919, 0.2892, 0.1542, 0.2552, 0.4149, 0.3397, 0.4137]])
torch.Size([2, 8])


In [32]:
import numpy as np

In [34]:
#torch to numpy array conversion
a=torch.ones(5)
print(a)

b=a.numpy()
print(b,type(b))

a=a+1
print(a)
print(b) #b is unchanged

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[1. 1. 1. 1. 1.]


In [35]:
#numpy array to torch conversion
a=np.ones(5)
print(a)

b=torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [36]:
import torch

# Create a tensor filled with ones that does not track gradients
x_no_grad = torch.ones(2, 2, requires_grad=False)
print(x_no_grad)

# Create a tensor filled with ones that tracks gradients
x_with_grad = torch.ones(2, 2, requires_grad=True)
print(x_with_grad)

'''requires_grad parameter is an optional argument that you can pass to torch.ones() to specify whether the tensor should track operations 
for gradient computation. Gradients are essential for automatic differentiation, which is a key component in training neural networks using 
techniques like backpropagation.'''

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
